server.port=9191
spring.cloud.config.enabled=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=prelogin-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://prelogin-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/prelogin/**

# Add these lines to your existing api-gateway.properties in the GitHub config repo

spring.cloud.gateway.server.webflux.routes[1].id=notification-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/notifications/**,/api/tasks/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=name=notificationCB,fallbackUri=forward:/fallback/notification

resilience4j.circuitbreaker.instances.notificationCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.notificationCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.notificationCB.permitted-number-of-calls-in-half-open-state=2


app.jwt.secret=755e4400ca9b850a43dd026081259da308374e93f7e85a5b3d205036c0d9fd4c
app.jwt.expiration=3600000
