server.port=9191
spring.cloud.config.enabled=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=PreLogin-Service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PreLogin-Service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/prelogin/**

app.jwt.secret=YourSuperSecretKeyWithAtLeast256BitsForHS256Algorithm
app.jwt.expiration=3600000
