server.port=8081

# Eureka Discovery
eureka.client.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_auth_db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration (Must be 32+ characters)
app.jwtSecret=LogiTrackSecureManagementSystemKey2026_Project
app.jwtExpirationMs=900000
# Force Swagger to use 3.0 instead of 3.1
springdoc.api-docs.version=openapi_3_0

# Default System Admin Credentials
app.admin.name=System Admin
app.admin.email=admin@logitrack.com
app.admin.password=Admin@123
