# 1. Identity
spring.application.name=prelogin-service
server.port=8085

# 2. Config Server Connection (Enable this!)
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://localhost:8888

# 3. Local Database (Only if not provided by Config Server)
spring.datasource.url=jdbc:mysql://localhost:3306/prelogin_db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# 4. Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# 5. Local Fallback for JWT (Prevents crash if Config Server is down)
app.jwt.secret=755e4400ca9b850a43dd026081259da308374e93f7e85a5b3d205036c0d9fd4c
app.jwt.expiration=3600000
